competitions:
  - id: 158146
    name: 3 Liga
    region: DEU
    supported: false
  - id: 10150305
    name: A League 2016/17
    region: AUS
    supported: false
  - id: 77
    name: Airtricity Premier Division
    region: IRL
    supported: false
  - id: 4431442
    name: Algerian Ligue 1
    region: DZA
    supported: false
  - id: 3792498
    name: Algerian U21 Ligue 1
    region: DZA
    supported: false
  - id: 10479956
    name: Austrian Bundesliga.
    region: AUT
    supported: false
  - id: 89979
    name: Belgian Jupiler League
    region: BEL
    supported: false
  - id: 3037492
    name: Beloften Pro League
    region: BEL
    supported: false
  - id: 4540630
    name: Brasiliense
    region: BRA
    supported: false
  - id: 835595
    name: Brazilian Baiano
    region: BRA
    supported: false
  - id: 89219
    name: Brazilian Cup
    region: BRA
    supported: false
  - id: 4517498
    name: Brazilian Paraense
    region: BRA
    supported: false
  - id: 439106
    name: Brazilian Paranaense
    region: BRA
    supported: false
  - id: 2490975
    name: Brazilian Paulista A1
    region: BRA
    supported: false
  - id: 2519611
    name: Brazilian Paulista A2
    region: BRA
    supported: false
  - id: 832265
    name: Brazilian Pernambucano
    region: BRA
    supported: false
  - id: 8740305
    name: Brazilian Primeira Liga
    region: BRA
    supported: false
  - id: 15
    name: Bulgarian Premier
    region: BGR
    supported: false
  - id: 59
    name: Bundesliga 1
    region: DEU
    supported: false
  - id: 61
    name: Bundesliga 2
    region: DEU
    supported: false
  - id: 1097799
    name: Central League
    region: GBR
    supported: false
  - id: 4760777
    name: Cheshire Senior Cup
    region: GBR
    supported: false
  - id: 744098
    name: Chilean Primera
    region: CHL
    supported: false
  - id: 844197
    name: Colombian Primera A
    region: COL
    supported: false
  - id: 856134
    name: Colombian Primera B
    region: COL
    supported: false
  - id: 1032778
    name: Copa Catalunya
    region: ESP
    supported: false
  - id: 12801
    name: Copa Del Rey
    region: ESP
    supported: false
  - id: 62815
    name: Copa Libertadores
    region: International
    supported: false
  - id: 1979279
    name: Copa Mexico
    region: MEX
    supported: false
  - id: 1874
    name: Coppa Italia
    region: ITA
    supported: false
  - id: 849268
    name: Coppa Italia Lega Pro
    region: ITA
    supported: false
  - id: 43079
    name: Coupe de France
    region: FRA
    supported: false
  - id: 17
    name: Croatian Division 1
    region: HRV
    supported: false
  - id: 10662505
    name: DFB Pokal
    region: DEU
    supported: false
  - id: 23
    name: Danish Superliga
    region: DNK
    supported: false
  - id: 9404054
    name: Dutch Eredivisie
    region: NLD
    supported: false
  - id: 2134
    name: EFL Cup
    region: GBR
    supported: false
  - id: 801976
    name: Egyptian Premier
    region: EGY
    supported: false
  - id: 97
    name: Ekstraklasa
    region: POL
    supported: false
  - id: 3039423
    name: Emir Cup
    region: KWT
    supported: false
  - id: 30558
    name: English FA Cup
    region: GBR
    supported: false
  - id: 31
    name: English Premier League
    region: GBR
    supported: false
  - id: 5614746
    name: FIFA World Cup 2018
    region: International
    supported: false
  - id: 10726751
    name: FNL Cup
    region: International
    supported: false
  - id: 10621540
    name: Fotbolti.net Cup - B Division
    region: ISL
    supported: false
  - id: 55
    name: French Ligue 1
    region: FRA
    supported: false
  - id: 57
    name: French Ligue 2
    region: FRA
    supported: false
  - id: 8616348
    name: Friendly
    region: International
    supported: false
  - id: 852459
    name: German Junioren Bundesliga
    region: DEU
    supported: false
  - id: 6435559
    name: Gloucester Senior Challenge Cup
    region: GBR
    supported: false
  - id: 833616
    name: Greek Football League
    region: GRC
    supported: false
  - id: 67
    name: Greek Super League
    region: GRC
    supported: false
  - id: 6569480
    name: Highland Football League
    region: GBR
    supported: false
  - id: 3085802
    name: Hong Kong Reserve League
    region: HKG
    supported: false
  - id: 94603
    name: Hungarian Cup
    region: HUN
    supported: false
  - id: 376041
    name: Indian I League
    region: IND
    supported: false
  - id: 845150
    name: Indonesian President's Cup
    region: IDN
    supported: false
  - id: 2883157
    name: Israeli Premier League (W)
    region: ISR
    supported: false
  - id: 4596938
    name: Isthmian Division One South
    region: GBR
    supported: false
  - id: 10729430
    name: Kazan Preseason Tournament
    region: International
    supported: false
  - id: 2489732
    name: Latvia Winter Cup
    region: LVA
    supported: false
  - id: 35
    name: League One
    region: GBR
    supported: false
  - id: 37
    name: League Two
    region: GBR
    supported: false
  - id: 944888
    name: Leinster Senior Cup
    region: IRL
    supported: false
  - id: 4905
    name: Liga 1
    region: ROU
    supported: false
  - id: 852072
    name: Malaysian FA Cup
    region: MYS
    supported: false
  - id: 7261832
    name: Maranhense 1 Division
    region: BRA
    supported: false
  - id: 5627174
    name: Mexican Primera Division
    region: MEX
    supported: false
  - id: 4540650
    name: NIFL Reserve League
    region: GBR
    supported: false
  - id: 39
    name: National League
    region: GBR
    supported: false
  - id: 41
    name: National League North
    region: GBR
    supported: false
  - id: 43
    name: National League South
    region: GBR
    supported: false
  - id: 5817495
    name: Northern Irish League Cup
    region: GBR
    supported: false
  - id: 6447264
    name: Northern Premier League Challenge Cup
    region: GBR
    supported: false
  - id: 4644728
    name: Northern Premier League Division One North
    region: GBR
    supported: false
  - id: 4540663
    name: Panama Liga Nacional de Ascenso
    region: PAN
    supported: false
  - id: 8825999
    name: Paulista A3
    region: BRA
    supported: false
  - id: 101
    name: Premier Division
    region: RUS
    supported: false
  - id: 10403285
    name: Premier League Cup
    region: GBR
    supported: false
  - id: 99
    name: Primeira Liga
    region: PRT
    supported: false
  - id: 117
    name: Primera Division
    region: ESP
    supported: false
  - id: 842258
    name: Qatari Stars League
    region: QAT
    supported: false
  - id: 65
    name: Regionalliga Sudwest
    region: DEU
    supported: false
  - id: 5808320
    name: SPFL Development League
    region: GBR
    supported: false
  - id: 6011072
    name: SPFL Development League 2
    region: GBR
    supported: false
  - id: 334679
    name: Scottish Challenge Cup
    region: GBR
    supported: false
  - id: 107
    name: Scottish Championship
    region: GBR
    supported: false
  - id: 409743
    name: Scottish Cup
    region: GBR
    supported: false
  - id: 109
    name: Scottish League One
    region: GBR
    supported: false
  - id: 111
    name: Scottish League Two
    region: GBR
    supported: false
  - id: 105
    name: Scottish Premiership
    region: GBR
    supported: false
  - id: 119
    name: Segunda Division
    region: ESP
    supported: false
  - id: 9513
    name: Segunda Liga
    region: PRT
    supported: false
  - id: 81
    name: Serie A
    region: ITA
    supported: false
  - id: 83
    name: Serie B
    region: ITA
    supported: false
  - id: 10699940
    name: South African Premier
    region: ZAF
    supported: false
  - id: 10615822
    name: Spanish Division de Honor U19
    region: ESP
    supported: false
  - id: 2608550
    name: Specials
    region: GBR
    supported: false
  - id: 10224373
    name: Stirling Sports Premiership 2016/17
    region: NZL
    supported: false
  - id: 133
    name: Swiss Super League
    region: CHE
    supported: false
  - id: 7129730
    name: The Championship
    region: GBR
    supported: true
  - id: 6103298
    name: Tunisian Ligue Professionelle 1
    region: TUN
    supported: false
  - id: 194215
    name: Turkish Super League
    region: TUR
    supported: false
  - id: 13051
    name: U19 Internationals
    region: International
    supported: false
  - id: 258537
    name: UAE Premier League
    region: ARE
    supported: false
  - id: 228
    name: UEFA Champions League
    region: International
    supported: false
  - id: 2005
    name: UEFA Europa League
    region: International
    supported: false
  - id: 7247362
    name: Ugandan Premier League
    region: UGA
    supported: false
  - id: 139
    name: Vischya Liga
    region: UKR
    supported: false
  - id: 252549
    name: Welsh Premier League
    region: GBR
    supported: false
  - id: 1242586
    name: Westfalenpokal
    region: DEU
    supported: false
  - id: 852011
    name: Xerox Super Cup
    region: JPN
    supported: false